import type { SiteConfig } from "./types";

/**
 * DEMO CLIENT — Highmark Ridge Golf Club (fictional).
 *
 * A mountain golf resort set on the plateau rim above the Dan River gorge
 * in the Blue Ridge Mountains of Patrick County, Virginia. Coordinates are
 * real terrain (≈36.71N, −80.45W) chosen for dramatic 3D flyovers; the
 * club, people, history and accolade sources are invented.
 *
 * Hole geometry was generated by scripts/layout-holes.mjs and is mirrored
 * in scripts/data/highmark-layout.json (consumed by the art generator).
 */
const config: SiteConfig = {
  identity: {
    courseName: "Highmark Ridge Golf Club",
    shortName: "Highmark Ridge",
    tagline: "At the rim of the Blue Ridge",
    established: 1929,
    logo: {
      crest: "/images/crest.svg",
      monogram: "/images/monogram.svg",
    },
    brandColors: {
      background: "#101511",
      backgroundRaised: "#18211b",
      primary: "#2e4d3a",
      accent: "#c2a35d",
      text: "#f2ede3",
      textDim: "#aaa593",
      line: "#3a4138",
    },
    fonts: {
      display: "Cormorant Garamond",
      body: "Jost",
    },
  },

  flags: {
    isResort: true,
    hasLodging: true,
    hasDining: true,
    hasWeddings: true,
    hasMembership: true,
    hasSpa: true,
    hasActivities: true,
    courseAccess: "semiPrivate",
    numberOfCourses: 1,
  },

  location: {
    address: {
      line1: "1 Highmark Ridge Lane",
      city: "Meadows of Dan",
      region: "Virginia",
      postalCode: "24120",
      country: "US",
    },
    coords: { lat: 36.7165, lng: -80.447 },
    elevationFt: 2940,
    regionNarrative:
      "Highmark Ridge sits on the last shelf of the Blue Ridge plateau, where Patrick County, Virginia falls away into the Dan River gorge. Mornings begin under cloudbanks that settle below the clubhouse; by afternoon the light runs long across laurel hollows, granite outcrops, and fairways that have followed the same contours since 1929. It is forty minutes from the Blue Ridge Parkway's quietest miles and a world away from everything else.",
    directions: [
      {
        from: "Roanoke, VA",
        text: "Take US-221 South to Floyd, then the Blue Ridge Parkway south to Meadows of Dan. Exit at milepost 178 and follow Highmark Ridge Lane 2.4 miles to the gatehouse. About 1 hour 25 minutes.",
      },
      {
        from: "Greensboro, NC",
        text: "Take US-220 North to Stuart, then VA-8 North up the mountain to Meadows of Dan. Turn left on Highmark Ridge Lane at the stone markers. About 1 hour 20 minutes.",
      },
      {
        from: "Charlotte, NC",
        text: "I-77 North through Mount Airy, then US-52 to VA-103 West and VA-8 North to Meadows of Dan. About 2 hours 15 minutes.",
      },
    ],
  },

  booking: {
    // Demo tee-sheet URL — replace with the client's provider (ForeUp,
    // GolfNow, Lightspeed, etc.). The button opens it in a new tab.
    teeTimeUrl: "https://example.com/tee-times/highmark-ridge",
    phone: "+1 (276) 555-0148",
    phoneHref: "tel:+12765550148",
    email: "reservations@highmark-ridge.example",
    bookingNote:
      "Public tee times are released 14 days in advance. Resort guests and Fellowship members enjoy preferred windows.",
  },

  courses: [
    {
      slug: "the-ridge",
      name: "The Ridge Course",
      designer: "Ellis Maybank, 1929 · Restored by Calder & Noe, 2008",
      yearBuilt: 1929,
      par: 72,
      signatureHoleNumber: 12,
      heroImage: {
        src: "/images/scenes/ridge-course.svg",
        alt: "Fairways of the Ridge Course folding across the plateau rim at dusk, with the Dan River gorge falling away beyond",
      },
      description:
        "Ellis Maybank routed the Ridge Course in 1929 with mule teams and a surveyor's eye for drama, letting the holes ride the plateau's folds rather than fight them. Nearly a century later the corridors remain his: fairways pitched against the contour, greens set on natural benches, and the gorge — always — at the edge of your vision. The 2008 restoration by Calder & Noe recovered Maybank's green pads and bunker lines from decades of overgrowth, returning a golden-age mountain course that plays firm, fast, and honest at 2,900 feet.",
      designerStory:
        "Maybank was a bridge engineer before he was an architect, and it shows: he trusted stone, fall lines, and the patience of walking golfers. He spent the summer of 1928 camped near the present sixteenth tee, mapping frost pockets and prevailing wind before a single tree was cleared. His field books — preserved in the clubhouse library — record the philosophy that still governs the course: “Find the hole that is already there.” When Calder & Noe began the restoration in 2007, those books were their only blueprint. Sand lines were cut back to Maybank's pencil widths, six lost back tees were rebuilt from his survey stakes, and the twelfth — his beloved gorge-rim one-shotter — was returned to the exact green pad he staked in 1929.",
      teeBoxes: [
        { id: "granite", name: "Granite", color: "#4b5563" },
        { id: "ridgeline", name: "Ridgeline", color: "#c2a35d" },
        { id: "laurel", name: "Laurel", color: "#2e7d4f" },
        { id: "meadow", name: "Meadow", color: "#b7c4cf" },
      ],
      ratings: [
        { teeId: "granite", rating: 74.6, slope: 144, yards: 7027 },
        { teeId: "ridgeline", rating: 72.3, slope: 138, yards: 6590 },
        { teeId: "laurel", rating: 70.0, slope: 131, yards: 6105 },
        { teeId: "meadow", rating: 66.7, slope: 119, yards: 5310 },
      ],
      gallery: [
        {
          src: "/images/gallery/gallery-01.svg",
          alt: "Dawn fog pooling beneath the first fairway",
        },
        {
          src: "/images/gallery/gallery-02.svg",
          alt: "The long shadows of late afternoon across the seventh fairway",
        },
        {
          src: "/images/gallery/gallery-03.svg",
          alt: "The twelfth green perched on the gorge rim at Window Rock",
        },
        {
          src: "/images/gallery/gallery-04.svg",
          alt: "Granite outcrops framing the sixteenth tee",
        },
        {
          src: "/images/gallery/gallery-05.svg",
          alt: "Cloudbank settling below the seventeenth fairway at dusk",
        },
        {
          src: "/images/gallery/gallery-06.svg",
          alt: "The walk home up the eighteenth toward the clubhouse lights",
        },
      ],
      holes: [
        {
          number: 1,
          name: "First Light",
          par: 4,
          yardages: { granite: 412, ridgeline: 385, laurel: 360, meadow: 310 },
          handicap: 9,
          description:
            "The opener falls away from the clubhouse terrace toward the southwest, a generous fairway tilted gently left toward two shoulder bunkers at the turn. The green sits on a low bench with the morning sun behind you — a quiet handshake before the mountain starts asking questions.",
          proTip:
            "The fairway runs hard left-to-right off the tee slope. Start your ball at the left bunker's edge and let the ground bring it back to center.",
          heroImage: {
            src: "/images/holes/hole-01.svg",
            alt: "Illustrated plan of hole 1, First Light, a par four falling southwest from the clubhouse",
          },
          tee: { lat: 36.716209, lng: -80.447432 },
          green: { lat: 36.714414, lng: -80.451016 },
          midpoints: [],
        },
        {
          number: 2,
          name: "Long Hollow",
          par: 5,
          yardages: { granite: 548, ridgeline: 515, laurel: 475, meadow: 415 },
          handicap: 5,
          description:
            "A three-shot journey west along the floor of Long Hollow, bending left around a laurel thicket at the 320 mark. The hollow funnels everything toward its creek seam, so position beats power twice here before a shallow green that accepts only a controlled third.",
          proTip:
            "Lay up to the right half of the fairway at the dogleg — the flat lie there is worth twenty yards of distance on your approach.",
          heroImage: {
            src: "/images/holes/hole-02.svg",
            alt: "Illustrated plan of hole 2, Long Hollow, a par five bending left through a wooded hollow",
          },
          tee: { lat: 36.71457, lng: -80.451354 },
          green: { lat: 36.714357, lng: -80.456829 },
          midpoints: [{ lat: 36.714936, lng: -80.454605 }],
        },
        {
          number: 3,
          name: "The Plunge",
          par: 3,
          yardages: { granite: 188, ridgeline: 175, laurel: 165, meadow: 140 },
          handicap: 17,
          description:
            "The first of Maybank's one-shotters plays across a wooded ravine to a green set into the far bank, two clubs of carry over a void that swallows anything timid. The putting surface is bigger than it looks from the tee — trust the number, not your eyes.",
          proTip:
            "The ravine exaggerates the distance. Take your honest club for 188 and swing at eighty percent; the green's backstop will gather a long ball.",
          heroImage: {
            src: "/images/holes/hole-03.svg",
            alt: "Illustrated plan of hole 3, The Plunge, a par three across a wooded ravine",
          },
          tee: { lat: 36.714697, lng: -80.456904 },
          green: { lat: 36.716049, lng: -80.457839 },
          midpoints: [],
        },
        {
          number: 4,
          name: "Laurel Climb",
          par: 4,
          yardages: { granite: 433, ridgeline: 405, laurel: 375, meadow: 325 },
          handicap: 3,
          description:
            "The hardest walk on the front nine climbs due north along a laurel-walled corridor, the fairway narrowing exactly where you want to bail out. The green is benched into the slope and putts a full club slower than anything you've seen yet.",
          proTip:
            "Add a club and a half on the approach — the climb plus the bench means your 150 number is really 170. Below the hole is the only good miss.",
          heroImage: {
            src: "/images/holes/hole-04.svg",
            alt: "Illustrated plan of hole 4, Laurel Climb, an uphill par four through laurel",
          },
          tee: { lat: 36.716281, lng: -80.457734 },
          green: { lat: 36.719736, lng: -80.456659 },
          midpoints: [],
        },
        {
          number: 5,
          name: "Crowfoot",
          par: 4,
          yardages: { granite: 395, ridgeline: 370, laurel: 345, meadow: 300 },
          handicap: 11,
          description:
            "Named for the three-toed scatter of bunkers at the landing zone, Crowfoot runs northeast along the property's high meadow with the long view to Buffalo Mountain opening on your right. A mid-iron approach to a perched green that releases hard to the back-right.",
          proTip:
            "Land your approach two paces onto the front edge — anything flown to the middle will chase over. The miss is short here, always short.",
          heroImage: {
            src: "/images/holes/hole-05.svg",
            alt: "Illustrated plan of hole 5, Crowfoot, a par four across the high meadow",
          },
          tee: { lat: 36.719884, lng: -80.456339 },
          green: { lat: 36.7217, lng: -80.45298 },
          midpoints: [],
        },
        {
          number: 6,
          name: "The Anvil",
          par: 3,
          yardages: { granite: 172, ridgeline: 160, laurel: 150, meadow: 130 },
          handicap: 15,
          description:
            "A short iron east and downhill to a green shaped like a smith's anvil — broad at the front, pinched at the back horn, ringed by five sandy hollows. Wind that you never felt on the tee works hardest over the green's open shoulder.",
          proTip:
            "Watch the flag at the seventh tee below — it tells the truth about the wind. When in doubt, one less club and a full swing.",
          heroImage: {
            src: "/images/holes/hole-06.svg",
            alt: "Illustrated plan of hole 6, The Anvil, a short downhill par three",
          },
          tee: { lat: 36.721677, lng: -80.452653 },
          green: { lat: 36.721407, lng: -80.45092 },
          midpoints: [],
        },
        {
          number: 7,
          name: "Saddleback",
          par: 5,
          yardages: { granite: 560, ridgeline: 525, laurel: 485, meadow: 425 },
          handicap: 1,
          description:
            "The number-one handicap rides a saddle of land southeast and downhill for 560 yards, doglegging right at the spine. Brave drivers who carry the inside ridge can reach in two; everyone else plays chess with a fairway that tilts toward trouble on both sides.",
          proTip:
            "The second shot is the hole. Pick the yardage that leaves your favorite full wedge — the green sits in a swale and blind half-shots are a bogey machine.",
          heroImage: {
            src: "/images/holes/hole-07.svg",
            alt: "Illustrated plan of hole 7, Saddleback, a long par five doglegging right along a ridgeline saddle",
          },
          tee: { lat: 36.721228, lng: -80.450653 },
          green: { lat: 36.717115, lng: -80.448473 },
          midpoints: [{ lat: 36.719232, lng: -80.448844 }],
        },
        {
          number: 8,
          name: "Old Orchard",
          par: 4,
          yardages: { granite: 430, ridgeline: 405, laurel: 375, meadow: 325 },
          handicap: 7,
          description:
            "Straight south through the remnant apple rows of the original Highmark farmstead, with gnarled centenarian trees guarding both elbows of the fairway. The deep green takes a long iron willingly but holds nothing hit with doubt.",
          proTip:
            "The orchard rows make the fairway look tighter than its forty yards. Commit to driver — the approach shortens dramatically from past the trees.",
          heroImage: {
            src: "/images/holes/hole-08.svg",
            alt: "Illustrated plan of hole 8, Old Orchard, a par four between old apple rows",
          },
          tee: { lat: 36.716797, lng: -80.448579 },
          green: { lat: 36.713287, lng: -80.449117 },
          midpoints: [],
        },
        {
          number: 9,
          name: "Homestead",
          par: 4,
          yardages: { granite: 381, ridgeline: 360, laurel: 330, meadow: 290 },
          handicap: 13,
          description:
            "The front nine closes with a gentle rise home, the clubhouse chimney your aiming point the whole way. A drumlin in the fairway's left half kicks balls right toward the ideal angle, and the green opens like a front porch to a running approach.",
          proTip:
            "This is the course's best birdie look after seven and eight have had their say. Aim the tee shot at the chimney and take dead aim with the wedge.",
          heroImage: {
            src: "/images/holes/hole-09.svg",
            alt: "Illustrated plan of hole 9, Homestead, a par four rising home to the clubhouse",
          },
          tee: { lat: 36.713287, lng: -80.448747 },
          green: { lat: 36.716303, lng: -80.447675 },
          midpoints: [{ lat: 36.714905, lng: -80.44798 }],
        },
        {
          number: 10,
          name: "The Gate",
          par: 4,
          yardages: { granite: 405, ridgeline: 380, laurel: 350, meadow: 305 },
          handicap: 10,
          description:
            "The inward nine departs east through a gateway of paired granite boulders that have flanked this tee since the course opened. The fairway runs away from you with the grain of the land, rewarding a drawn tee ball with sprinting yardage.",
          proTip:
            "A right-to-left ball shape gets a forty-yard ride off the chute slope. Hold the line over the right boulder and let it turn.",
          heroImage: {
            src: "/images/holes/hole-10.svg",
            alt: "Illustrated plan of hole 10, The Gate, a par four between granite boulders",
          },
          tee: { lat: 36.716453, lng: -80.446336 },
          green: { lat: 36.716917, lng: -80.442221 },
          midpoints: [],
        },
        {
          number: 11,
          name: "Foxglove",
          par: 4,
          yardages: { granite: 380, ridgeline: 355, laurel: 330, meadow: 285 },
          handicap: 18,
          description:
            "Short, downhill, and seductive, Foxglove tempts the bold to chase the green 380 yards below. Wildflower rough pinches the lay-up zone at 290, and the tiny green — the smallest on the course — repels everything that arrives without spin.",
          proTip:
            "The smart play is a 240 club to the fat of the fairway and a full wedge. The heroic line is there if you need a closing-stretch rally — just know the rough collects souvenirs.",
          heroImage: {
            src: "/images/holes/hole-11.svg",
            alt: "Illustrated plan of hole 11, Foxglove, a short downhill par four",
          },
          tee: { lat: 36.716769, lng: -80.441902 },
          green: { lat: 36.714036, lng: -80.440012 },
          midpoints: [],
        },
        {
          number: 12,
          name: "Window Rock",
          par: 3,
          yardages: { granite: 196, ridgeline: 185, laurel: 170, meadow: 150 },
          handicap: 14,
          description:
            "The signature. From a tee chiseled into the plateau's edge, the shot hangs for a held breath over the Dan River gorge — eight hundred feet of air off your right shoulder — to a green pad Maybank staked in 1929 and never moved. There is no safe side, only a true swing.",
          proTip:
            "The gorge updraft adds a half-club of float in the afternoon. Ride it: take one less and aim at the granite window in the far wall.",
          heroImage: {
            src: "/images/holes/hole-12.svg",
            alt: "Illustrated plan of hole 12, Window Rock, the signature par three along the gorge rim",
          },
          tee: { lat: 36.71376, lng: -80.440072 },
          green: { lat: 36.712312, lng: -80.440954 },
          midpoints: [],
        },
        {
          number: 13,
          name: "Dark Hollow",
          par: 5,
          yardages: { granite: 535, ridgeline: 505, laurel: 465, meadow: 405 },
          handicap: 4,
          description:
            "A brooding three-shotter that turns southwest into the property's deepest shade, bending left around a hemlock stand that drinks the afternoon light. The hollow narrows at every stage, ending at a green guarded by a spring-fed creek you'll hear before you see.",
          proTip:
            "Whatever your second shot, finish short of the 100-yard post — the creek hides in dead ground beyond it and the up-and-down from across is brutal.",
          heroImage: {
            src: "/images/holes/hole-13.svg",
            alt: "Illustrated plan of hole 13, Dark Hollow, a par five bending left into deep forest shade",
          },
          tee: { lat: 36.712188, lng: -80.44122 },
          green: { lat: 36.709807, lng: -80.445704 },
          midpoints: [{ lat: 36.711257, lng: -80.443958 }],
        },
        {
          number: 14,
          name: "The Traverse",
          par: 4,
          yardages: { granite: 460, ridgeline: 430, laurel: 400, meadow: 345 },
          handicap: 2,
          description:
            "The longest two-shotter on the mountain works west across a sidehill that never quite levels, demanding two struck shots with the ball above or below your feet. The green is mercifully large and open in front — Maybank's apology for the journey.",
          proTip:
            "Aim everything one flag-width uphill of your target and let the slope do the aiming. Par here gains a shot on the field every single day.",
          heroImage: {
            src: "/images/holes/hole-14.svg",
            alt: "Illustrated plan of hole 14, The Traverse, a long sidehill par four",
          },
          tee: { lat: 36.709864, lng: -80.446108 },
          green: { lat: 36.71122, lng: -80.450514 },
          midpoints: [],
        },
        {
          number: 15,
          name: "Springhouse",
          par: 4,
          yardages: { granite: 390, ridgeline: 365, laurel: 340, meadow: 295 },
          handicap: 12,
          description:
            "Past the stone springhouse that once chilled the farm's milk, fifteen climbs gently northwest to a punchbowl green ringed by shaggy-edged bunkers. The putting surface gathers shots from every direction — a rare moment of mountain generosity.",
          proTip:
            "Use the punchbowl: a running mid-iron released at the front-right slot feeds to center-green every time, wind be damned.",
          heroImage: {
            src: "/images/holes/hole-15.svg",
            alt: "Illustrated plan of hole 15, Springhouse, a par four to a punchbowl green",
          },
          tee: { lat: 36.711476, lng: -80.450698 },
          green: { lat: 36.714588, lng: -80.451666 },
          midpoints: [],
        },
        {
          number: 16,
          name: "The Sentinel",
          par: 3,
          yardages: { granite: 225, ridgeline: 210, laurel: 195, meadow: 170 },
          handicap: 16,
          description:
            "The last one-shotter is the longest, played northeast to a green standing alone on a granite shoulder beneath the course's oldest white oak — the Sentinel. The surface is huge and honest; the trouble is everything around it and the number in your head.",
          proTip:
            "This green takes a low runner beautifully. A punched long iron under the wind beats a soaring hybrid nine times out of ten.",
          heroImage: {
            src: "/images/holes/hole-16.svg",
            alt: "Illustrated plan of hole 16, The Sentinel, a long par three beneath an ancient oak",
          },
          tee: { lat: 36.714842, lng: -80.451581 },
          green: { lat: 36.716428, lng: -80.450392 },
          midpoints: [],
        },
        {
          number: 17,
          name: "Cloudbank",
          par: 5,
          yardages: { granite: 521, ridgeline: 490, laurel: 450, meadow: 395 },
          handicap: 6,
          description:
            "The penultimate hole climbs northeast in two broad terraces, swinging right at the crest where — on the right autumn morning — the valley below is a solid floor of cloud. Reachable downwind for the brave, but the green's false front has broken more cards than the gorge.",
          proTip:
            "Going for it in two? You must carry to the putting surface — the false front sheds anything landing short back forty yards. The lay-up to 90 is the percentage play.",
          heroImage: {
            src: "/images/holes/hole-17.svg",
            alt: "Illustrated plan of hole 17, Cloudbank, a climbing par five doglegging right",
          },
          tee: { lat: 36.716568, lng: -80.45009 },
          green: { lat: 36.719613, lng: -80.446588 },
          midpoints: [{ lat: 36.718705, lng: -80.448551 }],
        },
        {
          number: 18,
          name: "Long Shadow",
          par: 4,
          yardages: { granite: 396, ridgeline: 370, laurel: 345, meadow: 300 },
          handicap: 8,
          description:
            "Home, due south, with the clubhouse lanterns ahead and the whole western sky going amber on your right. A centerline bunker at 280 splits the fairway into a brave left lane and a safe right one, and the green sits in the building's long evening shadow — the finest place in Virginia to count a score.",
          proTip:
            "Take the right lane and the approach plays a half-club longer but dead straight. The left lane is for those who need birdie and believe.",
          heroImage: {
            src: "/images/holes/hole-18.svg",
            alt: "Illustrated plan of hole 18, Long Shadow, the finishing par four returning to the clubhouse",
          },
          tee: { lat: 36.719304, lng: -80.446448 },
          green: { lat: 36.716051, lng: -80.446332 },
          midpoints: [{ lat: 36.717511, lng: -80.446569 }],
        },
      ],
    },
  ],

  propertyMap: {
    center: { lat: 36.7158, lng: -80.4475 },
    zoom: 14.4,
    bearing: -17,
    pitch: 52,
    entry: {
      headline: "Highmark Ridge",
      subcopy:
        "Eighteen holes, one lodge, and three thousand acres of Blue Ridge plateau — explore the property from above.",
      cta: "Explore the Property",
    },
    pins: [
      {
        id: "clubhouse",
        coords: { lat: 36.7165, lng: -80.447 },
        category: "golf",
        title: "The Clubhouse",
        shortDesc:
          "Chestnut beams, a stone hearth taller than your caddie, and the 1929 field books of Ellis Maybank in the library. Golf shop, locker rooms, and the Anvil Tavern under one roof.",
        image: { src: "/images/scenes/clubhouse.svg", alt: "The stone and timber clubhouse at dusk with lit windows" },
        route: "/about",
      },
      {
        id: "first-tee",
        coords: { lat: 36.716209, lng: -80.447432 },
        category: "golf",
        title: "The First Tee",
        shortDesc:
          "First Light: a 412-yard handshake falling away to the southwest. Rounds begin here every eight minutes from first light to mid-afternoon.",
        image: { src: "/images/holes/hole-01.svg", alt: "Illustrated plan of the first hole" },
        route: "/course/the-ridge/holes?hole=1",
      },
      {
        id: "window-rock-tee",
        coords: { lat: 36.71376, lng: -80.440072 },
        category: "golf",
        title: "Window Rock — No. 12",
        shortDesc:
          "The signature par three over the Dan River gorge. Eight hundred feet of air, one true swing. The most photographed tee shot in the Virginia mountains.",
        image: { src: "/images/holes/hole-12.svg", alt: "Illustrated plan of the twelfth hole at the gorge rim" },
        route: "/course/the-ridge/holes?hole=12",
      },
      {
        id: "practice-meadow",
        coords: { lat: 36.7174, lng: -80.443915 },
        category: "practice",
        title: "The Practice Meadow",
        shortDesc:
          "A 320-yard grass range aimed at Buffalo Mountain, with short-game hollows, a wedge fan, and caddies who will happily read your divot patterns.",
        image: { src: "/images/scenes/range.svg", alt: "The grass practice range stretching toward distant ridgelines" },
        route: "/rates",
      },
      {
        id: "putting-green",
        coords: { lat: 36.716191, lng: -80.44594 },
        category: "practice",
        title: "The Big Putt",
        shortDesc:
          "Eleven thousand square feet of bentgrass beside the tenth tee, rolled to course speed every dawn. The evening putting league convenes at six.",
        image: { src: "/images/scenes/putting-green.svg", alt: "The expansive putting green beside the clubhouse" },
        route: "/rates",
      },
      {
        id: "wee-ridge",
        coords: { lat: 36.718717, lng: -80.44305 },
        category: "practice",
        title: "The Wee Ridge",
        shortDesc:
          "Six short holes of 65 to 110 yards tucked into the eastern meadow. Spikes optional, drinks encouraged, matches settled before dinner.",
        image: { src: "/images/scenes/short-course.svg", alt: "The six-hole short course in the eastern meadow" },
        route: "/rates",
      },
      {
        id: "lodge",
        coords: { lat: 36.718617, lng: -80.446629 },
        category: "lodging",
        title: "The Lodge",
        shortDesc:
          "Twenty-six rooms of timber, wool, and window-framed ridgelines above the seventeenth fairway. Fireplaces in every room; the gorge in most.",
        image: { src: "/images/scenes/lodge.svg", alt: "The timber lodge glowing at dusk above the seventeenth fairway" },
        route: "/stay",
      },
      {
        id: "cottages",
        coords: { lat: 36.717321, lng: -80.451817 },
        category: "lodging",
        title: "Ridgeline Cottages",
        shortDesc:
          "Eight two-bedroom cottages strung along the western rim, each with a screened porch, a wood stove, and a view that does the entertaining.",
        image: { src: "/images/scenes/cottages.svg", alt: "Stone cottages along the western ridgeline at golden hour" },
        route: "/stay",
      },
      {
        id: "ember-oak",
        coords: { lat: 36.718966, lng: -80.446893 },
        category: "dining",
        title: "Ember & Oak",
        shortDesc:
          "The signature dining room: open-hearth Appalachian cooking, a Virginia-leaning cellar, and the last light of the day on the western wall of glass.",
        image: { src: "/images/scenes/ember-oak.svg", alt: "The fire-lit dining room of Ember and Oak at evening" },
        route: "/dine",
      },
      {
        id: "anvil-tavern",
        coords: { lat: 36.718208, lng: -80.446429 },
        category: "dining",
        title: "The Anvil Tavern",
        shortDesc:
          "Burgers from the valley farms, taps from the Floyd breweries, and the day's matches re-litigated under the forge tools of the original farm smithy.",
        image: { src: "/images/scenes/anvil-tavern.svg", alt: "The warm interior of the Anvil Tavern with its copper bar" },
        route: "/dine",
      },
      {
        id: "the-still",
        coords: { lat: 36.718638, lng: -80.449084 },
        category: "amenity",
        title: "The Still — Spa & Bathhouse",
        shortDesc:
          "Cedar saunas, a cold plunge fed by the mountain spring, and treatments built around what eighteen holes of mountain golf does to a body.",
        image: { src: "/images/scenes/spa.svg", alt: "The spa bathhouse with cedar interior and soft lantern light" },
        route: "/stay#spa",
      },
      {
        id: "rim-pool",
        coords: { lat: 36.719626, lng: -80.448576 },
        category: "amenity",
        title: "The Rim Pool",
        shortDesc:
          "A heated infinity edge aimed straight down the gorge. Towels, shade, and a discreet bar service from May through October.",
        image: { src: "/images/scenes/pool.svg", alt: "The infinity pool at the plateau rim reflecting the evening sky" },
        route: "/stay",
      },
      {
        id: "wellness-pavilion",
        coords: { lat: 36.719294, lng: -80.444467 },
        category: "amenity",
        title: "Wellness Pavilion & Courts",
        shortDesc:
          "Two har-tru tennis courts, pickleball, a movement studio, and morning ridge-line yoga when the weather allows — which is most mornings.",
        image: { src: "/images/scenes/tennis.svg", alt: "Tennis courts beside the timber wellness pavilion" },
        route: "/stay",
      },
      {
        id: "meadow-lawn",
        coords: { lat: 36.712092, lng: -80.447675 },
        category: "amenity",
        title: "The Meadow Lawn",
        shortDesc:
          "An acre of level lawn against the western ridgeline — the property's gathering place for weddings, reunions, and the September oyster roast.",
        image: { src: "/images/scenes/meadow-lawn.svg", alt: "The open event lawn against the ridgeline under string lights" },
        route: "/events-weddings",
      },
      {
        id: "gorge-overlook",
        coords: { lat: 36.710492, lng: -80.449149 },
        category: "activity",
        title: "Window Rock Overlook",
        shortDesc:
          "A cantilevered ceremony terrace at the gorge rim, and the finest sunset seat on the property. A ten-minute walk from the Meadow Lawn.",
        image: { src: "/images/scenes/window-rock.svg", alt: "The cantilevered overlook terrace above the Dan River gorge" },
        route: "/events-weddings",
      },
      {
        id: "gorge-trailhead",
        coords: { lat: 36.715031, lng: -80.453837 },
        category: "activity",
        title: "Gorge Trails",
        shortDesc:
          "Eleven miles of maintained trail dropping from the rim to the river — waterfalls, rhododendron tunnels, and loops from forty minutes to four hours.",
        image: { src: "/images/scenes/trailhead.svg", alt: "A trail entering rhododendron forest at the gorge rim" },
        route: "/stay#activities",
      },
      {
        id: "rooker-pond",
        coords: { lat: 36.713503, lng: -80.441855 },
        category: "activity",
        title: "Rooker Pond",
        shortDesc:
          "Four spring-fed acres of brook and rainbow trout. Orvis rods at the boathouse, a guide on request, and a strict but merciful catch-and-release code.",
        image: { src: "/images/scenes/pond.svg", alt: "The still surface of Rooker Pond at dawn with rising mist" },
        route: "/stay#activities",
      },
    ],
  },

  lodging: [
    {
      id: "lodge",
      name: "The Lodge at Highmark",
      summary: "Twenty-six rooms of timber and wool above the seventeenth fairway.",
      description:
        "The Lodge is the quiet center of the resort: twenty-six rooms and suites built from chestnut reclaimed when the farm's great barn came down in 2009. Every room has a wood-burning fireplace laid nightly, a deep soaking tub, and windows set low so the ridgeline is the first thing you see without lifting your head from the pillow. No televisions in the rooms; there is one in the tavern, and it shows golf.",
      image: { src: "/images/scenes/lodge.svg", alt: "The timber lodge at dusk, windows glowing above the seventeenth fairway" },
      sleeps: 2,
      priceFrom: 495,
      details: [
        "26 rooms & suites, all with wood-burning fireplaces",
        "Gorge-view and fairway-view aspects",
        "Daily firewood, turndown, and morning coffee service",
        "Two-night minimum on peak weekends",
      ],
    },
    {
      id: "cottages",
      name: "Ridgeline Cottages",
      summary: "Eight two-bedroom stone cottages strung along the western rim.",
      description:
        "The cottages are for staying longer: two bedrooms, a proper sitting room with a wood stove, a small kitchen the chefs will happily provision, and a screened porch hung exactly where the evening light lands. Cottage guests get first call on sunrise tee times and the loan of a club Land Rover for Parkway wandering.",
      image: { src: "/images/scenes/cottages.svg", alt: "A stone cottage with a lit screened porch at golden hour" },
      sleeps: 4,
      priceFrom: 825,
      details: [
        "Two bedrooms, two baths, full sitting room",
        "Screened porch with western exposure",
        "Provisioned kitchen on request",
        "Dogs welcomed with enthusiasm and biscuits",
      ],
    },
    {
      id: "gorge-house",
      name: "The Gorge House",
      summary: "A five-bedroom private estate at the quiet southern rim.",
      description:
        "The original Highmark family home, rebuilt stone by stone at the property's southern edge, is taken whole: five bedrooms, a great room with a twelve-foot hearth, a private chef's kitchen, and a lawn that ends where the gorge begins. It comes with a dedicated house team, a private golf cart fleet, and the only key to the rim gate — beyond which is a bench, a fire ring, and eight hundred feet of evening air.",
      image: { src: "/images/scenes/gorge-house.svg", alt: "The stone estate house at the southern rim under an evening sky" },
      sleeps: 10,
      priceFrom: 3200,
      details: [
        "Five bedrooms, five and a half baths",
        "Dedicated house manager and daily chef service available",
        "Private fire ring at the gorge rim",
        "Three-night minimum; buyout inquiries welcomed",
      ],
    },
  ],

  dining: [
    {
      id: "ember-oak",
      name: "Ember & Oak",
      style: "Open-hearth Appalachian — dinner",
      hours: "Wednesday–Sunday, 5:30–10 p.m.",
      dressCode: "Mountain elegant — jackets never required, boots always forgiven",
      summary: "The signature room: fire-cooked Appalachian fare and a Virginia-leaning cellar.",
      description:
        "Everything at Ember & Oak passes over the twelve-foot open hearth: trout from cold mountain water, dry-aged beef from the valley below, spring vegetables blistered in the coals and finished with cider vinegars made in-house. The cellar runs deep on Virginia — Ankida Ridge pinots, Early Mountain blends — alongside the Burgundies the sommelier can't quit. Ask for the western window at half past golden hour.",
      image: { src: "/images/scenes/ember-oak.svg", alt: "The fire-lit dining room of Ember and Oak with its wall of western glass" },
    },
    {
      id: "anvil-tavern",
      name: "The Anvil Tavern",
      style: "Clubhouse tavern — lunch & evening",
      hours: "Daily, 11 a.m.–11 p.m.",
      summary: "The nineteenth hole, under the forge tools of the original farm smithy.",
      description:
        "The Tavern occupies the clubhouse's oldest corner, where the farm's blacksmith once worked, and his tools still hang over the copper bar. The kitchen does the honest things flawlessly: a smashed double from valley beef, hand-cut fries in beef fat, trout cakes, and a transcendent chess pie. Twelve taps lean local — Floyd, Roanoke, Mount Airy — and the porch seats are dealt by seniority of that day's scorecard.",
      image: { src: "/images/scenes/anvil-tavern.svg", alt: "The copper bar of the Anvil Tavern beneath hanging forge tools" },
    },
    {
      id: "first-light-porch",
      name: "The First Light Porch",
      style: "Coffee & provisions — morning",
      hours: "Daily, 6–11 a.m.",
      summary: "Coffee, ham biscuits, and the sunrise over the first tee.",
      description:
        "A small porch counter beside the golf shop pouring a dark, serious house roast from a Floyd County roaster, alongside ham biscuits, sorghum oats, and wax-paper packets of shortbread sized exactly for a back-nine pocket. Most of the season's best weather happens here before eight a.m., and the regulars know it.",
      image: { src: "/images/scenes/first-light-porch.svg", alt: "Morning light across the porch counter and the first tee beyond" },
    },
  ],

  activities: [
    {
      id: "gorge-trails",
      name: "The Gorge Trails",
      summary:
        "Eleven miles of maintained trail from rim to river: waterfalls, rhododendron tunnels, and the old logging grades, in loops of forty minutes to four hours. Trail maps and walking sticks at the lodge desk.",
      image: { src: "/images/scenes/trailhead.svg", alt: "A trail entering a rhododendron tunnel at the gorge rim" },
      season: "Year-round",
    },
    {
      id: "fly-fishing",
      name: "Fly Fishing at Rooker Pond",
      summary:
        "Four spring-fed acres holding brook and rainbow trout of suspicious size. Orvis rods and flies at the boathouse, casting lessons on the lawn, and a guide for the river below by arrangement.",
      image: { src: "/images/scenes/pond.svg", alt: "Mist rising off Rooker Pond at first light" },
      season: "March – November",
    },
    {
      id: "sporting-clays",
      name: "The High Bench Clays",
      summary:
        "A ten-station sporting clays course set along the northern woodline, with loaner Berettas, instruction for first-timers, and a standing wager between the golf shop and the kitchen.",
      image: { src: "/images/scenes/clays.svg", alt: "A clays station bench at the edge of the northern woodline" },
      season: "Year-round",
    },
    {
      id: "dark-sky",
      name: "Dark-Sky Evenings",
      summary:
        "The plateau has some of the darkest measured sky in Virginia. Telescopes come out on the Cloudbank deck on clear new-moon nights, with hot toddies and a star chart you can keep.",
      image: { src: "/images/scenes/dark-sky.svg", alt: "The Milky Way over the ridgeline from the Cloudbank deck" },
      season: "New-moon weeks",
    },
  ],

  spa: {
    name: "The Still — Spa & Bathhouse",
    summary: "Cedar heat, spring-fed cold, and treatments built for golfers' bodies.",
    description:
      "The Still borrows its rhythm from the old farm springhouse: heat, cold, rest, repeat. Cedar saunas look into the trees, the plunge pool runs a bracing 55 degrees straight from the mountain spring, and the treatment list is built around what mountain golf actually does to hips, forearms, and feet. Book the bathhouse circuit before a round or the recovery sequence after; book both and cancel your afternoon.",
    image: { src: "/images/scenes/spa.svg", alt: "The cedar bathhouse interior at the Still, lit by low lanterns" },
    treatments: [
      { name: "The Bathhouse Circuit", duration: "60 min", price: 95 },
      { name: "After-Round Recovery", duration: "50 min", price: 165 },
      { name: "Stone & Cedar Massage", duration: "80 min", price: 240 },
      { name: "Ridge Botanical Facial", duration: "50 min", price: 185 },
      { name: "The Mountain Air Ritual", duration: "110 min", price: 320 },
    ],
  },

  weddings: {
    headline: "Married at the rim of the sky",
    summary:
      "Ceremonies at the gorge edge, dinners under the lodge beams, and a property that empties of everything but your people.",
    description:
      "Highmark Ridge hosts a small number of weddings each year — never more than one on the property at a time. Ceremonies happen at the Window Rock Overlook as the gorge fills with evening light, or on the Meadow Lawn against the western ridgeline. Dinner moves to Granite Hall or under sailcloth on the lawn; the kitchen cooks over fire, the cellar opens, and the last dance tends to migrate to the Tavern. Full-property buyouts give you the lodge, the cottages, and eighteen holes for your guests' idle hours.",
    image: { src: "/images/scenes/weddings.svg", alt: "A wedding dinner under string lights on the Meadow Lawn at dusk" },
    venues: [
      {
        name: "Window Rock Overlook",
        capacity: 90,
        setting: "Cantilevered ceremony terrace at the gorge rim — evening light, eight hundred feet of air, no second location like it",
        image: { src: "/images/scenes/window-rock.svg", alt: "The cantilevered ceremony terrace above the gorge" },
      },
      {
        name: "The Meadow Lawn",
        capacity: 220,
        setting: "An acre of level lawn against the western ridgeline, strung with lights and open to the sunset",
        image: { src: "/images/scenes/meadow-lawn.svg", alt: "The event lawn under string lights at dusk" },
      },
      {
        name: "Granite Hall",
        capacity: 160,
        setting: "The lodge's vaulted timber hall — twin stone hearths, chestnut beams, and weather-proof certainty",
        image: { src: "/images/scenes/granite-hall.svg", alt: "The vaulted timber event hall with twin stone fireplaces" },
      },
    ],
  },

  rates: {
    intro:
      "Green fees include a forecaddie (walking is encouraged and the course was built for it), range balls at the Practice Meadow, and the kind of pace of play that only a mountain with no real estate can promise.",
    tables: [
      {
        title: "Daily Fee — Public Play",
        note: "Public tee times released 14 days in advance.",
        rows: [
          {
            season: "Peak Season",
            dates: "April 15 – June 30 · September 1 – November 1",
            weekday: 295,
            weekend: 345,
            twilight: 165,
          },
          {
            season: "High Summer",
            dates: "July 1 – August 31",
            weekday: 245,
            weekend: 285,
            twilight: 135,
          },
          {
            season: "Quiet Season",
            dates: "November 2 – April 14 (weather permitting)",
            weekday: 165,
            weekend: 195,
            twilight: 95,
          },
        ],
      },
      {
        title: "Resort Guests",
        note: "For guests of the Lodge, Cottages, and Gorge House. Preferred tee windows and replay privileges included.",
        rows: [
          {
            season: "Peak Season",
            dates: "April 15 – June 30 · September 1 – November 1",
            weekday: 240,
            weekend: 280,
            twilight: 135,
            includes: "Same-day replay $95",
          },
          {
            season: "High Summer",
            dates: "July 1 – August 31",
            weekday: 195,
            weekend: 225,
            twilight: 115,
            includes: "Same-day replay $75",
          },
          {
            season: "Quiet Season",
            dates: "November 2 – April 14 (weather permitting)",
            weekday: 135,
            weekend: 160,
            twilight: 85,
            includes: "Same-day replay $55",
          },
        ],
      },
    ],
    notes: [
      "Twilight begins at 3:00 p.m. April–October and 1:30 p.m. in the quiet season.",
      "Caddies (single or double bag) available by advance request through the golf shop.",
      "Juniors 17 and under play for half the prevailing rate after 1 p.m. with a paying adult.",
      "Carts are available but the Ridge walks beautifully — it was designed for it.",
      "Rain checks issued for rounds halted before the 10th tee by weather.",
    ],
    membership: {
      headline: "The Highmark Fellowship",
      intro:
        "A small membership keeps the tee sheet honest and the locker room familiar. Fellowship is by introduction, with a candidacy round and dinner — the committee insists on meeting your short game and your table manners in the same week.",
      tiers: [
        {
          name: "Full Fellowship",
          initiation: 30000,
          duesMonthly: 720,
          blurb: "The whole property, all season, with the longest booking horizon on the mountain.",
          perks: [
            "Unlimited golf with 21-day booking window",
            "Full lodge, dining, and spa privileges with member pricing",
            "Locker, bag storage, and club care included",
            "Six accompanied guest rounds monthly",
          ],
        },
        {
          name: "Mountain (Weekday)",
          initiation: 14000,
          duesMonthly: 420,
          blurb: "Monday through Thursday golf for those who've arranged their lives correctly.",
          perks: [
            "Unlimited weekday golf, 14-day booking window",
            "Weekend twilight access September–April",
            "Dining and spa privileges with member pricing",
            "Three accompanied guest rounds monthly",
          ],
        },
        {
          name: "Beyond the Ridge (National)",
          initiation: 9000,
          duesMonthly: 295,
          blurb: "For Fellows whose primary residence is more than 100 miles from the gatehouse.",
          perks: [
            "Twelve rounds per season, transferable to family",
            "Priority lodge booking with member rates",
            "Full privileges during any property stay",
            "Reciprocal courtesies with allied mountain clubs",
          ],
        },
      ],
      contactNote:
        "Inquiries to the Membership Secretary via the contact page or +1 (276) 555-0148. Candidacies for the coming season close October 1.",
    },
  },

  about: {
    historyHeadline: "Ninety-seven years at the rim",
    history: [
      "The land was a high farm first — apples, cattle, and a blacksmith's forge serving the wagon road that crept along the plateau rim. In 1928 the Highmark family, flush from Danville textile money and obsessed with the golf they'd seen in the Highlands of Scotland, hired a bridge engineer named Ellis Maybank to find a course in their three thousand acres. Maybank spent a summer camped at the rim before he moved a single stone. The course opened on June 14, 1929 — four months before the crash that should have killed it.",
      "It survived because it was loved disproportionately to its means. Through the lean decades the family kept nine holes mowed with a tractor and faith, and the course earned a quiet, ardent following among golfers who'd heard rumors of a gorge-rim par three somewhere above Meadows of Dan. The full eighteen returned to play in 1954, and for half a century Highmark Ridge stayed what it had always been: a family farm with a remarkable golf problem.",
      "In 2007 the fourth generation made the decision their great-grandparents would have recognized — to share the place properly. The restoration architects Calder & Noe spent two seasons returning Maybank's lines from his own field books, the chestnut barn became the bones of the lodge, and in 2011 Highmark Ridge opened its gates as a resort. The brief given to every member of staff since has not changed by a word: keep it a farm that golfs, never a brand that farms.",
    ],
    accolades: [
      {
        kind: "ranking",
        source: "Mountain Golf Journal — No. 4 Mountain Course in America",
        year: 2025,
      },
      {
        kind: "press",
        source: "The Fairway Review",
        year: 2024,
        quote: "Eighteen holes suspended between weather and stone — the most transporting golf experience east of the Rockies.",
      },
      {
        kind: "award",
        source: "Southern Links Quarterly — Restoration of the Decade",
        year: 2018,
      },
      {
        kind: "ranking",
        source: "Resort & Estate — Top 20 Golf Resorts in the South",
        year: 2025,
      },
    ],
    gallery: [
      { src: "/images/gallery/gallery-01.svg", alt: "Dawn fog pooling beneath the first fairway", category: "Course" },
      { src: "/images/gallery/gallery-02.svg", alt: "Late light across the seventh fairway saddle", category: "Course" },
      { src: "/images/gallery/gallery-03.svg", alt: "The twelfth green at Window Rock above the gorge", category: "Course" },
      { src: "/images/gallery/gallery-04.svg", alt: "Granite outcrops at the sixteenth tee", category: "Course" },
      { src: "/images/gallery/gallery-05.svg", alt: "Cloud floor below the seventeenth at dawn", category: "Course" },
      { src: "/images/gallery/gallery-06.svg", alt: "The eighteenth fairway running home to the clubhouse", category: "Course" },
      { src: "/images/gallery/gallery-07.svg", alt: "The lodge great room and its twin hearths", category: "Lodge" },
      { src: "/images/gallery/gallery-08.svg", alt: "A cottage porch facing the western ridgeline", category: "Lodge" },
      { src: "/images/gallery/gallery-09.svg", alt: "The hearth line at Ember and Oak mid-service", category: "Dining" },
      { src: "/images/gallery/gallery-10.svg", alt: "Chess pie and coffee at the Anvil Tavern", category: "Dining" },
      { src: "/images/gallery/gallery-11.svg", alt: "The rim pool at blue hour", category: "Property" },
      { src: "/images/gallery/gallery-12.svg", alt: "The Milky Way over the plateau from the Cloudbank deck", category: "Property" },
    ],
    staff: [
      {
        name: "Marion Tate",
        role: "Managing Director",
        bio: "Marion came to the Ridge from fifteen years running Highland lodges in Scotland, and swears the fog here is better. She reads the tee sheet like a seating chart and knows every dog on property by name.",
        image: { src: "/images/staff/staff-01.svg", alt: "Crest portrait mark for Marion Tate, Managing Director" },
      },
      {
        name: "Wes Calloway",
        role: "Director of Golf",
        bio: "A Patrick County native who caddied here at fourteen and never really left. Wes keeps the game honest, the caddie corps sharp, and a standing offer: beat him from the Granites and your round is free.",
        image: { src: "/images/staff/staff-02.svg", alt: "Crest portrait mark for Wes Calloway, Director of Golf" },
      },
      {
        name: "Priya Raman",
        role: "Director of Agronomy",
        bio: "Priya turned down flatter, easier ground in the Sandhills to grow bentgrass at 2,900 feet. Her greens roll true at dawn and her frost-delay forecasts are accurate to the minute, which around here counts as sorcery.",
        image: { src: "/images/staff/staff-03.svg", alt: "Crest portrait mark for Priya Raman, Director of Agronomy" },
      },
      {
        name: "Theo Marsh",
        role: "Executive Chef",
        bio: "Theo cooked in Charleston and Lyon before the hearth at Ember & Oak brought him up the mountain. He buys whole animals from the valley, knows every forager in three counties, and holds the kitchen's side of the clays wager.",
        image: { src: "/images/staff/staff-04.svg", alt: "Crest portrait mark for Theo Marsh, Executive Chef" },
      },
    ],
  },

  announcement: {
    enabled: true,
    text: "Summer evenings at the Ridge — twilight rounds from $115 after 3 p.m.",
    href: "/rates",
    linkLabel: "View rates",
  },

  seo: {
    siteUrl: "https://highmark-ridge.example",
    description:
      "Highmark Ridge Golf Club — a 1929 Ellis Maybank mountain course and lodge at the rim of the Dan River gorge in the Blue Ridge Mountains of Virginia. Eighteen holes at 2,900 feet, twenty-six rooms, and the signature Window Rock par three.",
    keywords: [
      "mountain golf Virginia",
      "Blue Ridge golf resort",
      "golf lodge Virginia",
      "Highmark Ridge",
      "Dan River gorge golf",
    ],
  },
};

export default config;
